name: Build Unsigned IPA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Verify Project Structure
        run: |
          echo "Project contents:"
          ls -la
          echo "\nXcode project contents:"
          ls -la Countdown.xcodeproj/
          echo "\nProject.pbxproj contents:"
          cat Countdown.xcodeproj/project.pbxproj

      - name: Create Build Directory
        run: mkdir -p build

      - name: Build Archive
        run: |
          xcodebuild clean archive \
            -project Countdown.xcodeproj \
            -scheme Countdown \
            -configuration Release \
            -archivePath build/Countdown.xcarchive \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            PROVISIONING_PROFILE="" \
            GCC_OPTIMIZATION_LEVEL=0 \
            SWIFT_OPTIMIZATION_LEVEL="-Onone" \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Generate Export Options
        run: |
          cat > build/ExportOptions.plist << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>manual</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>teamID</key>
              <string></string>
              <key>provisioningProfiles</key>
              <dict/>
          </dict>
          </plist>
          EOL

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath build/Countdown.xcarchive \
            -exportPath build/Countdown \
            -exportOptionsPlist build/ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Countdown-unsigned
          path: build/Countdown/Countdown.ipa
          retention-days: 7

      - name: Clean Up
        if: always()
        run: |
          rm -rf build/
