name: Build Unsigned IPA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Diagnose Project File
        run: |
          echo "Project file contents:"
          cat Countdown.xcodeproj/project.pbxproj
          
          echo "\nChecking for common issues..."
          if ! grep -q "rootObject =" Countdown.xcodeproj/project.pbxproj; then
            echo "Error: Missing rootObject"
          fi
          
          if ! grep -q "isa = PBXProject;" Countdown.xcodeproj/project.pbxproj; then
            echo "Error: Missing PBXProject declaration"
          fi

      - name: Attempt Project File Fix
        run: |
          cd Countdown.xcodeproj
          # Backup original file
          cp project.pbxproj project.pbxproj.backup
          
          # Fix common issues
          sed -i '' '1i\
          // !$*UTF8*$!
          ' project.pbxproj
          
          # Ensure PBXProject section exists
          if ! grep -q "isa = PBXProject;" project.pbxproj; then
            sed -i '' '/^[[:space:]]*{/a\
            \tisa = PBXProject;
            ' project.pbxproj
          fi
          
          # Add missing isa declarations
          sed -i '' 's/^\([[:space:]]*\){[[:space:]]*$/\1{ isa = PBXBuildFile;/g' project.pbxproj
          
          echo "Modified project file contents:"
          cat project.pbxproj

      - name: Verify Xcode Project
        run: |
          xcodebuild -list -project Countdown.xcodeproj || {
            echo "Project verification failed. Uploading project file for inspection."
            mkdir -p artifacts
            cp -r Countdown.xcodeproj artifacts/
            exit 1
          }

      - name: Upload Project File for Inspection
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-project
          path: artifacts/
          retention-days: 1

      - name: Create Build Directory
        if: success()
        run: mkdir -p build

      - name: Build for iOS
        run: |
          xcodebuild clean archive \
            -project Countdown.xcodeproj \
            -scheme Countdown \
            -configuration Release \
            -archivePath build/Countdown.xcarchive \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty && exit ${PIPESTATUS[0]}
            
      # Add this step to verify sound files are in the bundle
      - name: Verify Resource Files
        run: |
          find build/Countdown.xcarchive -name "*.mp3"

      - name: Create IPA Structure
        if: success()
        run: |
          mkdir -p build/Payload
          cp -r build/DerivedData/Build/Products/Release-iphoneos/Countdown.app build/Payload/
          cd build
          zip -qr ../Countdown.ipa Payload

      - name: Upload IPA
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Countdown.ipa
          path: Countdown.ipa
          retention-days: 7
          if-no-files-found: error

      - name: Clean Up
        if: always()
        run: |
          rm -rf build/
          rm -f Countdown.ipa
