name: Build Unsigned IPA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Show Project Structure
        run: |
          echo "Project contents:"
          ls -la
          echo "\nXcode project contents:"
          ls -la Countdown.xcodeproj/

      - name: Create Build Directory
        run: mkdir -p build

      - name: Build for iOS
        run: |
          xcodebuild clean build \
            -project Countdown.xcodeproj \
            -scheme Countdown \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build/DerivedData \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="" \
            ONLY_ACTIVE_ARCH=NO \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Create IPA Structure
        run: |
          mkdir -p build/Payload
          cp -r build/DerivedData/Build/Products/Release-iphoneos/Countdown.app build/Payload/
          cd build && zip -r Countdown.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Countdown-unsigned
          path: build/Countdown.ipa
          retention-days: 7

      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            build/DerivedData/**/*.log
            *.log
          retention-days: 1

      - name: Clean Up
        if: always()
        run: |
          rm -rf build/
