name: Countdown

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode
      uses: apple-actions/setup-xcode@v1
    - name: Build with Xcode
      run: |
        xcodebuild -workspace Countdown.xcworkspace -scheme Countdown -sdk iphoneos -configuration Release clean build
    - name: Run tests
      run: |
        xcodebuild test -workspace Countdown.xcworkspace -scheme Countdown -destination 'platform=iOS Simulator,name=iPhone 12' -enableCodeCoverage YES
