name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Xcode dependencies
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch
    - name: Build with Xcode
      run: |
        xcodebuild -workspace project.xcworkspace -scheme Countdown -sdk iphoneos -configuration Release clean build
    - name: Run tests
      run: |
        xcodebuild test -workspace project.xcworkspace -scheme Countdown -destination 'platform=iOS Simulator,name=iPhone 12' -enableCodeCoverage YES
