# Workflow to build and test a Swift project for Countdown-App
name: Swift Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Swift
    - name: Setup Swift
      run: |
        echo "Swift version:"
        swift --version

    # Build the Swift project
    - name: Build Project
      run: swift build -v

    # Run tests
    - name: Run Tests
      run: swift test -v
